name: Run autopenguin on everything
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: ["master"]
    paths: [".github/workflows/*"]
  # If I trigger this from one of my other workflows
  repository_dispatch:
    types: [chart_update]    

env:
  GITHUB_PAGES_BRANCH: gh-pages
  HELM_CHARTS_SOURCE: "./autopenguin/repos"
  HELM_VERSION: 3.2.0
  GITHUB_PAGES_REPO: geek-cookbook/charts
  GITHUB_USERNAME: geek-cookbook

jobs:
  deploy:
    name: Publish charts
    runs-on: ubuntu-latest

    steps:

    - name: Download latest build
      run: |
        curl \
        $(\
        curl -s https://github_actor:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/geek-cookbook/autopenguin/actions/artifacts | \
        jq '. as $in | [.artifacts[].id] | max as $max | $in | .artifacts[] | select (.id == $max) | .archive_download_url' -r \
        ) \
        -u github_actor:${{ secrets.GITHUB_TOKEN }} -L | \
        python2 -c "import zipfile,sys,StringIO;zipfile.ZipFile(StringIO.StringIO(sys.stdin.read())).extractall(sys.argv[1] if len(sys.argv) == 2 else '.')" autopenguin
        
        
      # Blame github for the unreasonably long command
    - name: Run it!
      run: |
        cd autopenguin
        chmod +x ./autopenguin
        ./autopenguin render -u github_actor -t ${{ secrets.AUTOCHEF_TOKEN }} -w

    - name: Checkout charts repo
      uses: actions/checkout@v2
      with:    
        repository: ${{ env.GITHUB_PAGES_REPO }}
        ref: ${{ env.GITHUB_PAGES_BRANCH }}   
        path: to_publish

    - name: Lint and package charts
      run: |  
        set -x 
        helm version
        find "${{ env.HELM_CHARTS_SOURCE }}" -mindepth 4 -maxdepth 4 -type d | grep charts/ | grep -v bitnami | while read chart; do
          if [ -f $chart/Chart.yaml ]; then
            echo ">>> helm lint $chart"
            helm lint "$chart"

            chart_name="`basename "$chart"`"
            echo ">>> helm package -d to_publish/$chart_name $chart"
            mkdir -p "to_publish/$chart_name"
            helm dep update $chart
            helm package -d "to_publish/$chart_name" "$chart"
          fi
        done
        helm repo index to_publish
    
    # For reason for this, see https://github.com/ad-m/github-push-action/issues/52
    - name: Remove troublesome extra header from actions/checkout results
      run: |
        cd to_publish
        git config --local --unset-all "http.https://github.com/.extraheader"
        git config --global user.email "autopenguin@funkypenguin.co.nz"
        git config --global user.name "AutoPenguin"        
        git add .
        git commit -m 'I <3 charts'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.AUTOCHEF_TOKEN }}
        directory: to_publish
        branch: ${{ env.GITHUB_PAGES_BRANCH }}
        repository: ${{ env.GITHUB_PAGES_REPO }}
      env:
        GITHUB_ACTOR: funkypenguin-autochef
